# Generated by Django 4.1 on 2023-01-04 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taxi.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ("id",),
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=taxi.models.path_to_image
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=taxi.models.path_to_image
            ),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxi.car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxi.car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.AddField(
            model_name="car",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="taxi.comment"
            ),
        ),
    ]
