# Generated by Django 4.1.12 on 2024-02-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="content",
            field=models.TextField(default="", max_length=255),
        ),
    ]
