# Generated by Django 4.1 on 2022-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
