# Generated by Django 4.1 on 2022-11-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_carcomments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carcomments",
            name="drivers",
        ),
    ]
