# Generated by Django 4.1.12 on 2024-02-01 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_newspaper_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="published_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
