# Generated by Django 4.1 on 2022-11-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_reviewrating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewRating",
        ),
    ]
