# Generated by Django 4.1.12 on 2024-02-01 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0003_newspaper_published_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspaper",
            old_name="redactors",
            new_name="publishers",
        ),
    ]
