# Generated by Django 4.1 on 2022-11-03 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_remove_carcomments_drivers"),
    ]

    operations = [
        migrations.AddField(
            model_name="carcomments",
            name="driver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
