# Generated by Django 4.1 on 2022-11-03 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_carcomments_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carcomments",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_comments_car",
                to="taxi.car",
            ),
        ),
        migrations.AlterField(
            model_name="carcomments",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
