# Generated by Django 4.1.12 on 2024-02-02 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0004_rename_redactors_newspaper_publishers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspaper",
            old_name="publishers",
            new_name="drivers",
        ),
    ]
