# Generated by Django 4.1 on 2022-11-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
