# Generated by Django 4.1.12 on 2024-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0005_rename_publishers_newspaper_drivers"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default=25),
        ),
    ]
