# Generated by Django 4.1 on 2022-11-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0005_alter_carcomments_car_alter_carcomments_driver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carcomments",
            old_name="body",
            new_name="text",
        ),
    ]
