# Generated by Django 4.1.12 on 2024-02-02 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0006_redactor_years_of_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redactor",
            name="license_number",
        ),
    ]
