# Generated by Django 4.1 on 2022-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0006_rename_body_carcomments_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carcomments",
            name="active",
        ),
        migrations.AlterField(
            model_name="carcomments",
            name="text",
            field=models.TextField(verbose_name="text"),
        ),
    ]
