# Generated by Django 4.1 on 2022-11-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0006_driver_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="avatar",
            field=models.ImageField(upload_to="static/images"),
        ),
    ]
