# Generated by Django 4.1.12 on 2024-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0007_remove_redactor_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default=2),
        ),
    ]
