# Generated by Django 4.1 on 2022-11-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_alter_driver_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
