# Generated by Django 4.1.12 on 2024-02-02 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0008_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspaper",
            old_name="drivers",
            new_name="publishers",
        ),
    ]
