# Generated by Django 4.1 on 2022-11-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0009_alter_carcomments_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
