# Generated by Django 4.1 on 2022-11-09 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0011_alter_driver_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like",
                    models.BooleanField(default=False, verbose_name="Like"),
                ),
                (
                    "car_comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxi.carcomments",
                        verbose_name="car_comment",
                    ),
                ),
                (
                    "liked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="liked_by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment like",
                "verbose_name_plural": "Comment likes",
            },
        ),
    ]
