# Generated by Django 4.1 on 2022-11-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0012_alter_car_options_commentlike"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommentLike",
        ),
    ]
