# Generated by Django 4.1 on 2022-12-15 01:30

from django.db import migrations, models
import taxi.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0012_alter_car_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=taxi.models.path_to_image
            ),
        ),
    ]
