# Generated by Django 4.1 on 2022-11-09 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0013_delete_commentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="carcomments",
            name="likes",
            field=models.ManyToManyField(
                related_name="car_comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
