# Generated by Django 4.1 on 2022-11-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0014_carcomments_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carcomments",
            name="text",
            field=models.CharField(max_length=255, verbose_name="text"),
        ),
    ]
